language: java
jdk:
  - oraclejdk8
env:
  - EXTERNAL_REDIS=true
services:
   - redis-server
script: 
   - ./gradlew test
   - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)   
